//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDBAN()
        {
            this.CHITIETHDBANs = new HashSet<CHITIETHDBAN>();
        }
    
        public string MAHD { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public int NGUOILAP_ID { get; set; }
        public int NGUOIMUA_ID { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDBAN> CHITIETHDBANs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG1 { get; set; }
    }
}
