//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHLAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHLAM()
        {
            this.CHAMCONGs = new HashSet<CHAMCONG>();
        }
    
        public int MALICH { get; set; }
        public int NGUOIDUNG_ID { get; set; }
        public System.DateTime NGAYLAM { get; set; }
        public string CALAM { get; set; }
        public Nullable<System.TimeSpan> GIOVAO { get; set; }
        public Nullable<System.TimeSpan> GIORA { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONG> CHAMCONGs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
