//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCTHDNhap
    {
        public int LogID { get; set; }
        public string MAHDNHAP { get; set; }
        public string MASP { get; set; }
        public Nullable<int> SOLUONGTN { get; set; }
        public Nullable<decimal> DONGIANHAP { get; set; }
        public Nullable<decimal> THANHTIENN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> LoggedAt { get; set; }
    }
}
