//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_SIEUTHIMINI_TIEMTAPHOAEntities1 : DbContext
    {
        public QL_SIEUTHIMINI_TIEMTAPHOAEntities1()
            : base("name=QL_SIEUTHIMINI_TIEMTAPHOAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHAMCONG> CHAMCONGs { get; set; }
        public virtual DbSet<CHITIETHDBAN> CHITIETHDBANs { get; set; }
        public virtual DbSet<CHITIETHDNHAP> CHITIETHDNHAPs { get; set; }
        public virtual DbSet<CONGNO> CONGNOes { get; set; }
        public virtual DbSet<HANGTRUNGBAY> HANGTRUNGBAYs { get; set; }
        public virtual DbSet<HDBAN> HDBANs { get; set; }
        public virtual DbSet<HDNHAP> HDNHAPs { get; set; }
        public virtual DbSet<LICHLAM> LICHLAMs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<LogChiTietHDBan> LogChiTietHDBans { get; set; }
        public virtual DbSet<LogCTHDNhap> LogCTHDNhaps { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<OTP_LOG> OTP_LOG { get; set; }
        public virtual DbSet<PHIEUTHANHTOAN> PHIEUTHANHTOANs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<VAITRO> VAITROes { get; set; }
        public virtual DbSet<V_CONGNO_PHAITRA> V_CONGNO_PHAITRA { get; set; }
        public virtual DbSet<V_HOADON_CHITIET> V_HOADON_CHITIET { get; set; }
        public virtual DbSet<V_SANPHAM_HSD> V_SANPHAM_HSD { get; set; }
        public virtual DbSet<V_SANPHAM_NHACUNGCAP> V_SANPHAM_NHACUNGCAP { get; set; }
        public virtual DbSet<V_TONKHO> V_TONKHO { get; set; }
        public virtual DbSet<VIEW_ThongKeDoanhThu> VIEW_ThongKeDoanhThu { get; set; }
    
        public virtual int sp_ChamCong(string username, Nullable<System.DateTime> ngayLam, Nullable<System.TimeSpan> gioVao, Nullable<System.TimeSpan> gioRa)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var ngayLamParameter = ngayLam.HasValue ?
                new ObjectParameter("NgayLam", ngayLam) :
                new ObjectParameter("NgayLam", typeof(System.DateTime));
    
            var gioVaoParameter = gioVao.HasValue ?
                new ObjectParameter("GioVao", gioVao) :
                new ObjectParameter("GioVao", typeof(System.TimeSpan));
    
            var gioRaParameter = gioRa.HasValue ?
                new ObjectParameter("GioRa", gioRa) :
                new ObjectParameter("GioRa", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChamCong", usernameParameter, ngayLamParameter, gioVaoParameter, gioRaParameter);
        }
    
        public virtual ObjectResult<sp_GetDanhSachCongNo_Result> sp_GetDanhSachCongNo(string maNCC, string trangThai, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<bool> chiQuaHan, Nullable<bool> chiConNo)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var chiQuaHanParameter = chiQuaHan.HasValue ?
                new ObjectParameter("ChiQuaHan", chiQuaHan) :
                new ObjectParameter("ChiQuaHan", typeof(bool));
    
            var chiConNoParameter = chiConNo.HasValue ?
                new ObjectParameter("ChiConNo", chiConNo) :
                new ObjectParameter("ChiConNo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDanhSachCongNo_Result>("sp_GetDanhSachCongNo", maNCCParameter, trangThaiParameter, tuNgayParameter, denNgayParameter, chiQuaHanParameter, chiConNoParameter);
        }
    
        public virtual ObjectResult<sp_GetHDBanListByMASP_Result> sp_GetHDBanListByMASP(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetHDBanListByMASP_Result>("sp_GetHDBanListByMASP", mASPParameter);
        }
    
        public virtual ObjectResult<sp_GetNhapByUser_Result> sp_GetNhapByUser(string uSERNAME)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetNhapByUser_Result>("sp_GetNhapByUser", uSERNAMEParameter);
        }
    
        public virtual ObjectResult<sp_LichLam_GetByWeek_Result> sp_LichLam_GetByWeek(string role, string username, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LichLam_GetByWeek_Result>("sp_LichLam_GetByWeek", roleParameter, usernameParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int sp_TaoCongNoTuHDNhap(string maHDNhap, string maNCC, Nullable<decimal> soTienPhaiTra, Nullable<System.DateTime> hanTra, string ghiChu, ObjectParameter maCongNo)
        {
            var maHDNhapParameter = maHDNhap != null ?
                new ObjectParameter("MaHDNhap", maHDNhap) :
                new ObjectParameter("MaHDNhap", typeof(string));
    
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var soTienPhaiTraParameter = soTienPhaiTra.HasValue ?
                new ObjectParameter("SoTienPhaiTra", soTienPhaiTra) :
                new ObjectParameter("SoTienPhaiTra", typeof(decimal));
    
            var hanTraParameter = hanTra.HasValue ?
                new ObjectParameter("HanTra", hanTra) :
                new ObjectParameter("HanTra", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoCongNoTuHDNhap", maHDNhapParameter, maNCCParameter, soTienPhaiTraParameter, hanTraParameter, ghiChuParameter, maCongNo);
        }
    
        public virtual int sp_ThanhToanCongNo(string maCongNo, Nullable<decimal> soTienTra, string ghiChu, ObjectParameter maPTT)
        {
            var maCongNoParameter = maCongNo != null ?
                new ObjectParameter("MaCongNo", maCongNo) :
                new ObjectParameter("MaCongNo", typeof(string));
    
            var soTienTraParameter = soTienTra.HasValue ?
                new ObjectParameter("SoTienTra", soTienTra) :
                new ObjectParameter("SoTienTra", typeof(decimal));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToanCongNo", maCongNoParameter, soTienTraParameter, ghiChuParameter, maPTT);
        }
    
        public virtual ObjectResult<SP_ThongKeLuong_Result> SP_ThongKeLuong(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ThongKeLuong_Result>("SP_ThongKeLuong", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<usp_CanhBaoTonKho_Result> usp_CanhBaoTonKho(Nullable<int> nguongTon, Nullable<int> nguongHSD)
        {
            var nguongTonParameter = nguongTon.HasValue ?
                new ObjectParameter("NguongTon", nguongTon) :
                new ObjectParameter("NguongTon", typeof(int));
    
            var nguongHSDParameter = nguongHSD.HasValue ?
                new ObjectParameter("NguongHSD", nguongHSD) :
                new ObjectParameter("NguongHSD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CanhBaoTonKho_Result>("usp_CanhBaoTonKho", nguongTonParameter, nguongHSDParameter);
        }
    
        public virtual int usp_DuaHangLenKe(string maSP, Nullable<int> soLuong)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DuaHangLenKe", maSPParameter, soLuongParameter);
        }
    
        public virtual ObjectResult<usp_SanPhamSapHetHan_Result> usp_SanPhamSapHetHan(Nullable<int> ngayHetHan)
        {
            var ngayHetHanParameter = ngayHetHan.HasValue ?
                new ObjectParameter("NgayHetHan", ngayHetHan) :
                new ObjectParameter("NgayHetHan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SanPhamSapHetHan_Result>("usp_SanPhamSapHetHan", ngayHetHanParameter);
        }
    
        public virtual ObjectResult<usp_ThongKeDoanhThu_Result> usp_ThongKeDoanhThu(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ThongKeDoanhThu_Result>("usp_ThongKeDoanhThu", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<usp_TimSanPhamTheoGia_Result> usp_TimSanPhamTheoGia(Nullable<decimal> giaMin, Nullable<decimal> giaMax)
        {
            var giaMinParameter = giaMin.HasValue ?
                new ObjectParameter("GiaMin", giaMin) :
                new ObjectParameter("GiaMin", typeof(decimal));
    
            var giaMaxParameter = giaMax.HasValue ?
                new ObjectParameter("GiaMax", giaMax) :
                new ObjectParameter("GiaMax", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimSanPhamTheoGia_Result>("usp_TimSanPhamTheoGia", giaMinParameter, giaMaxParameter);
        }
    }
}
