//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHANHTOAN
    {
        public string MAPTT { get; set; }
        public string MACONGNO { get; set; }
        public decimal SOTIENTRA { get; set; }
        public System.DateTime NGAYTRA { get; set; }
        public string GHICHU { get; set; }
    
        public virtual CONGNO CONGNO { get; set; }
    }
}
