//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.NGUOIDUNGs = new HashSet<NGUOIDUNG>();
            this.OTP_LOG = new HashSet<OTP_LOG>();
        }
    
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string MAROLE { get; set; }
        public string EMAIL { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYKHOA { get; set; }
        public Nullable<System.DateTime> NGAYMOKHOA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTP_LOG> OTP_LOG { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
