//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CONGNO_PHAITRA
    {
        public string MACONGNO { get; set; }
        public string MAHD { get; set; }
        public string MANCC { get; set; }
        public string TENNHACUNGCAP { get; set; }
        public System.DateTime NGAYPHATSINH { get; set; }
        public decimal SOTIENPHAITRA { get; set; }
        public decimal DATHANHTOAN { get; set; }
        public Nullable<decimal> CONLAI { get; set; }
        public Nullable<System.DateTime> HANTRA { get; set; }
        public string TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
    }
}
