//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public int MACHAM { get; set; }
        public int MANV { get; set; }
        public System.DateTime NGAYLAM { get; set; }
        public Nullable<System.TimeSpan> GIOVAO { get; set; }
        public Nullable<System.TimeSpan> GIORA { get; set; }
        public Nullable<double> SOGIO { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> LICHLAM_ID { get; set; }
    
        public virtual LICHLAM LICHLAM { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
