//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHDNHAP
    {
        public string MAHDNHAP { get; set; }
        public string MASP { get; set; }
        public int SOLUONGTN { get; set; }
        public int DONGIANHAP { get; set; }
        public Nullable<int> THANHTIENN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual HDNHAP HDNHAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
