//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP_LOG
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string OTP_CODE { get; set; }
        public System.DateTime CREATE_AT { get; set; }
        public System.DateTime EXPIRY_AT { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
