//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHDBANs = new HashSet<CHITIETHDBAN>();
            this.CHITIETHDNHAPs = new HashSet<CHITIETHDNHAP>();
        }
    
        public string MALOAI { get; set; }
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string HINH { get; set; }
        public Nullable<System.DateTime> NSX { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string MANCC { get; set; }
        public string BARCODE { get; set; }
        public string BARCODE_IMAGE { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDBAN> CHITIETHDBANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDNHAP> CHITIETHDNHAPs { get; set; }
        public virtual HANGTRUNGBAY HANGTRUNGBAY { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
