//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HOADON_CHITIET
    {
        public string MAHD { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public int NGUOILAP_ID { get; set; }
        public string TenNguoiLap { get; set; }
        public int NGUOIMUA_ID { get; set; }
        public string TenNguoiMua { get; set; }
        public string GHICHU { get; set; }
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    }
}
