//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TONKHO
    {
        public string MASP { get; set; }
        public string MALOAI { get; set; }
        public string TENSP { get; set; }
        public Nullable<System.DateTime> NSX { get; set; }
        public Nullable<System.DateTime> HSD { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public string MANCC { get; set; }
        public int SOLUONGNHAP { get; set; }
        public int SOLUONGBAN { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
    }
}
