//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_ThongKeDoanhThu
    {
        public Nullable<System.DateTime> Ngay { get; set; }
        public decimal DoanhThu { get; set; }
        public int ChiPhi { get; set; }
        public Nullable<decimal> LoiNhuan { get; set; }
    }
}
